version: '3.8'

services:
  postgres:
    image: pgvector/pgvector:pg17
    container_name: postgres-pgvector
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    ports:
      - "${POSTGRES_PORT}:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - mastra-network
    restart: unless-stopped

volumes:
  postgres_data:

networks:
  mastra-network:
    driver: bridge